title: Luis Felipe Solís
email: solislf@gmail.com
url: https://luisfelipesolis.com

# Generate permalinks for all of the pages of the form '/page_title/'
permalink: /:title/

keep_files:
  # Keep ./_site/CNAME file for github pages
  - 'CNAME'
  # Keep the styles, scripts because gulp builds them before building the jekyll site
  - 'assets'

# Social
github_url: https://github.com/feli-solis
linkedin_url: https://www.linkedin.com/in/luis-felipe-solis-8b1a0ab6

# Excludes
exclude:
  - gulpfile.js
  - package-lock.json
  - package.json
  - node_modules
  # Not really needed. Jekyll ignores directories that begin with underscore
  - _assets
  